INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (1, 'Baelhadj', 'Hadj Aissa', '1997-11-05');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (2, 'had', 'ji', '1997-11-05');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (3, 'Tara', 'Kitto', '1989-03-07');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (4, 'Janifer', 'Cranmor', '2009-10-08');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (5, 'Enrika', 'Hendrikse', '1980-03-15');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (6, 'Licha', 'Olenchenko', '1948-03-13');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (7, 'Rosamond', 'Strank', '1966-06-15');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (8, 'Katrina', 'Watkiss', '1960-10-26');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (9, 'Jeniece', 'Jubb', '1952-08-02');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (10, 'Brucie', 'Comberbeach', '1970-06-27');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (11, 'Llewellyn', 'McKue', '1985-02-22');
INSERT INTO library.author (authorId, authorFirstName, authorLastName, authorBirthDay) VALUES (12, 'Jecho', 'Stoppe', '1980-10-07');
